In [10]:
import pandas as pd

df = pd.read_csv("../data/raw/madrid_housing.csv")

In [11]:
print("Shape:", df.shape)      # e.g. (21742, 58)
df.info()                     # shows columns, types, null counts
df.head()                     # first 5 rows

Shape: (21742, 58)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21742 entries, 0 to 21741
Data columns (total 58 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    21742 non-null  int64
 1   id                            21742 non-null  int64
 2   title                         21742 non-null  object
 3   subtitle                      21742 non-null  object
 4   sq_mt_built                   21616 non-null  float64
 5   sq_mt_useful                  8228 non-null   float64
 6   n_rooms                       21742 non-null  int64
 7   n_bathrooms                   21726 non-null  float64
 8   n_floors                      1437 non-null   float64
 9   sq_mt_allotment               1432 non-null   float64
 10  latitude                      0 non-null      float64
 11  longitude                     0 non-null      float64
 12  raw_address                   16277 non-null  object
 13  is_exact_address_hidden       21742 non-null  bool
 14  street_name                   15837 non-null  object
 15  street_number                 6300 non-null   object
 16  portal                        0 non-null      float64
 17  floor                         19135 non-null  object
 18  is_floor_under                20572 non-null  object
 19  door                          0 non-null      float64
 20  neighborhood_id               21742 non-null  object
 21  operation                     21742 non-null  object
 22  rent_price                    21742 non-null  int64
 23  rent_price_by_area            0 non-null      float64
 24  is_rent_price_known           21742 non-null  bool
 25  buy_price                     21742 non-null  int64
 26  buy_price_by_area             21742 non-null  int64
 27  is_buy_price_known            21742 non-null  bool
 28  house_type_id                 21351 non-null  object
 29  is_renewal_needed             21742 non-null  bool
 30  is_new_development            20750 non-null  object
 31  built_year                    10000 non-null  float64
 32  has_central_heating           13608 non-null  object
 33  has_individual_heating        13608 non-null  object
 34  are_pets_allowed              0 non-null      float64
 35  has_ac                        11211 non-null  object
 36  has_fitted_wardrobes          13399 non-null  object
 37  has_lift                      19356 non-null  object
 38  is_exterior                   18699 non-null  object
 39  has_garden                    1556 non-null   object
 40  has_pool                      5171 non-null   object
 41  has_terrace                   9548 non-null   object
 42  has_balcony                   3321 non-null   object
 43  has_storage_room              7698 non-null   object
 44  is_furnished                  0 non-null      float64
 45  is_kitchen_equipped           0 non-null      float64
 46  is_accessible                 4074 non-null   object
 47  has_green_zones               4057 non-null   object
 48  energy_certificate            21742 non-null  object
 49  has_parking                   21742 non-null  bool
 50  has_private_parking           0 non-null      float64
 51  has_public_parking            0 non-null      float64
 52  is_parking_included_in_price  7719 non-null   object
 53  parking_price                 7719 non-null   float64
 54  is_orientation_north          11358 non-null  object
 55  is_orientation_west           11358 non-null  object
 56  is_orientation_south          11358 non-null  object
 57  is_orientation_east           11358 non-null  object
dtypes: bool(5), float64(17), int64(6), object(30)
memory usage: 8.9+ MB

,Unnamed: 0,id,title,subtitle,sq_mt_built,sq_mt_useful,n_rooms,n_bathrooms,n_floors,sq_mt_allotment,...,energy_certificate,has_parking,has_private_parking,has_public_parking,is_parking_included_in_price,parking_price,is_orientation_north,is_orientation_west,is_orientation_south,is_orientation_east
0,0,21742,"Piso en venta en calle de Godella, 64","San Cristóbal, Madrid",64.0,60.0,2,1.0,NaN,NaN,...,D,False,NaN,NaN,NaN,NaN,False,True,False,False
1,1,21741,Piso en venta en calle de la del Manojo de Rosas,"Los Ángeles, Madrid",70.0,NaN,3,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,21740,"Piso en venta en calle del Talco, 68","San Andrés, Madrid",94.0,54.0,2,2.0,NaN,NaN,...,no indicado,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,21739,Piso en venta en calle Pedro Jiménez,"San Andrés, Madrid",64.0,NaN,2,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,False,False,True,False
4,4,21738,Piso en venta en carretera de Villaverde a Val...,"Los Rosales, Madrid",108.0,90.0,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,True,True,True,True

In [12]:
null_counts = df.isnull().sum()
null_pct    = (null_counts / len(df)) * 100
missing_df = pd.DataFrame({
    "null_count": null_counts,
    "null_pct":   null_pct.round(2)
}).sort_values("null_pct", ascending=False)

missing_df

                              null_count  null_pct
has_private_parking                21742    100.00
door                               21742    100.00
portal                             21742    100.00
is_furnished                       21742    100.00
rent_price_by_area                 21742    100.00
longitude                          21742    100.00
latitude                           21742    100.00
has_public_parking                 21742    100.00
is_kitchen_equipped                21742    100.00
are_pets_allowed                   21742    100.00
sq_mt_allotment                    20310     93.41
n_floors                           20305     93.39
has_garden                         20186     92.84
has_balcony                        18421     84.73
has_green_zones                    17685     81.34
is_accessible                      17668     81.26
has_pool                           16571     76.22
street_number                      15442     71.02
has_storage_room                   14044     64.59
parking_price                      14023     64.50
is_parking_included_in_price       14023     64.50
sq_mt_useful                       13514     62.16
has_terrace                        12194     56.08
built_year                         11742     54.01
has_ac                             10531     48.44
is_orientation_north               10384     47.76
is_orientation_south               10384     47.76
is_orientation_west                10384     47.76
is_orientation_east                10384     47.76
has_fitted_wardrobes                8343     38.37
has_central_heating                 8134     37.41
has_individual_heating              8134     37.41
street_name                         5905     27.16
raw_address                         5465     25.14
is_exterior                         3043     14.00
floor                               2607     11.99
has_lift                            2386     10.97
is_floor_under                      1170      5.38
is_new_development                   992      4.56
house_type_id                        391      1.80
sq_mt_built                          126      0.58
n_bathrooms                           16      0.07
energy_certificate                     0      0.00
has_parking                            0      0.00
Unnamed: 0                             0      0.00
id                                     0      0.00
is_buy_price_known                     0      0.00
buy_price_by_area                      0      0.00
buy_price                              0      0.00
is_rent_price_known                    0      0.00
rent_price                             0      0.00
operation                              0      0.00
neighborhood_id                        0      0.00
is_exact_address_hidden                0      0.00
n_rooms                                0      0.00
subtitle                               0      0.00
title                                  0      0.00
is_renewal_needed                      0      0.00

In [13]:
# 1. Data types
dtypes = df.dtypes
print(dtypes)

# 2. Number of unique values per column
uniques = df.nunique(dropna=False)
unique_df = pd.DataFrame({
    "dtype": dtypes,
    "unique_vals": uniques
}).sort_values("unique_vals")

unique_df

Unnamed: 0                        int64
id                                int64
title                            object
subtitle                         object
sq_mt_built                     float64
sq_mt_useful                    float64
n_rooms                           int64
n_bathrooms                     float64
n_floors                        float64
sq_mt_allotment                 float64
latitude                        float64
longitude                       float64
raw_address                      object
is_exact_address_hidden            bool
street_name                      object
street_number                    object
portal                          float64
floor                            object
is_floor_under                   object
door                            float64
neighborhood_id                  object
operation                        object
rent_price                        int64
rent_price_by_area              float64
is_rent_price_known                bool
buy_price                         int64
buy_price_by_area                 int64
is_buy_price_known                 bool
house_type_id                    object
is_renewal_needed                  bool
is_new_development               object
built_year                      float64
has_central_heating              object
has_individual_heating           object
are_pets_allowed                float64
has_ac                           object
has_fitted_wardrobes             object
has_lift                         object
is_exterior                      object
has_garden                       object
has_pool                         object
has_terrace                      object
has_balcony                      object
has_storage_room                 object
is_furnished                    float64
is_kitchen_equipped             float64
is_accessible                    object
has_green_zones                  object
energy_certificate               object
has_parking                        bool
has_private_parking             float64
has_public_parking              float64
is_parking_included_in_price     object
parking_price                   float64
is_orientation_north             object
is_orientation_west              object
is_orientation_south             object
is_orientation_east              object
dtype: object

                                dtype  unique_vals
are_pets_allowed              float64            1
door                          float64            1
is_buy_price_known               bool            1
has_public_parking            float64            1
has_private_parking           float64            1
is_rent_price_known              bool            1
rent_price_by_area            float64            1
portal                        float64            1
is_kitchen_equipped           float64            1
latitude                      float64            1
longitude                     float64            1
is_furnished                  float64            1
operation                      object            1
has_pool                       object            2
has_terrace                    object            2
has_fitted_wardrobes           object            2
is_renewal_needed                bool            2
has_garden                     object            2
has_ac                         object            2
has_balcony                    object            2
has_storage_room               object            2
is_exact_address_hidden          bool            2
is_accessible                  object            2
has_green_zones                object            2
has_parking                      bool            2
has_individual_heating         object            3
has_central_heating            object            3
is_orientation_west            object            3
is_new_development             object            3
is_parking_included_in_price   object            3
is_orientation_south           object            3
is_floor_under                 object            3
has_lift                       object            3
is_exterior                    object            3
is_orientation_north           object            3
is_orientation_east            object            3
house_type_id                  object            5
n_floors                      float64            7
energy_certificate             object           10
n_bathrooms                   float64           17
n_rooms                         int64           19
floor                          object           20
parking_price                 float64           85
neighborhood_id                object          126
subtitle                       object          146
built_year                    float64          156
sq_mt_allotment               float64          357
sq_mt_useful                  float64          409
street_number                  object          421
sq_mt_built                   float64          679
rent_price                      int64         1671
buy_price                       int64         2403
buy_price_by_area               int64         5643
street_name                    object         6178
raw_address                    object         9667
title                          object        10736
id                              int64        21742
Unnamed: 0                      int64        21742

In [14]:
# 1. Identify boolean columns
bool_cols = df.select_dtypes(include='bool').columns.tolist()
print("Boolean columns:", bool_cols)

# 2. Show unique counts for boolean columns
bool_uniques = df[bool_cols].nunique(dropna=False)
print("Boolean unique counts:")
print(bool_uniques)

# 3. Now look at the other columns
other_cols = df.columns.difference(bool_cols)

# 4. Data types & unique values for non-boolean
dtypes_other = df[other_cols].dtypes
uniques_other = df[other_cols].nunique(dropna=False)

unique_df_other = pd.DataFrame({
    "dtype": dtypes_other,
    "unique_vals": uniques_other
}).sort_values("unique_vals")

unique_df_other

Boolean columns: ['is_exact_address_hidden', 'is_rent_price_known', 'is_buy_price_known', 'is_renewal_needed', 'has_parking']
Boolean unique counts:
is_exact_address_hidden    2
is_rent_price_known        1
is_buy_price_known         1
is_renewal_needed          2
has_parking                2
dtype: int64

                                dtype  unique_vals
is_furnished                  float64            1
has_public_parking            float64            1
has_private_parking           float64            1
latitude                      float64            1
longitude                     float64            1
is_kitchen_equipped           float64            1
operation                      object            1
portal                        float64            1
are_pets_allowed              float64            1
rent_price_by_area            float64            1
door                          float64            1
is_accessible                  object            2
has_terrace                    object            2
has_storage_room               object            2
has_pool                       object            2
has_garden                     object            2
has_green_zones                object            2
has_fitted_wardrobes           object            2
has_balcony                    object            2
has_ac                         object            2
is_new_development             object            3
is_parking_included_in_price   object            3
is_orientation_north           object            3
is_orientation_east            object            3
is_orientation_west            object            3
is_orientation_south           object            3
is_exterior                    object            3
is_floor_under                 object            3
has_lift                       object            3
has_individual_heating         object            3
has_central_heating            object            3
house_type_id                  object            5
n_floors                      float64            7
energy_certificate             object           10
n_bathrooms                   float64           17
n_rooms                         int64           19
floor                          object           20
parking_price                 float64           85
neighborhood_id                object          126
subtitle                       object          146
built_year                    float64          156
sq_mt_allotment               float64          357
sq_mt_useful                  float64          409
street_number                  object          421
sq_mt_built                   float64          679
rent_price                      int64         1671
buy_price                       int64         2403
buy_price_by_area               int64         5643
street_name                    object         6178
raw_address                    object         9667
title                          object        10736
id                              int64        21742
Unnamed: 0                      int64        21742

In [15]:
# Column‐wise missing %
missing_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)
print("Top 10 most‐missing columns:\n", missing_pct.head(10))

# Row‐wise missing count distribution
row_missing = df.isnull().sum(axis=1)
print("Rows with >50% features missing:",
      (row_missing > (df.shape[1]/2)).sum())

Top 10 most‐missing columns:
 has_private_parking    100.0
door                   100.0
portal                 100.0
is_furnished           100.0
rent_price_by_area     100.0
longitude              100.0
latitude               100.0
has_public_parking     100.0
is_kitchen_equipped    100.0
are_pets_allowed       100.0
dtype: float64
Rows with >50% features missing: 3682